### ISSUE TITLE
Map utility county column name

### ISSUE THREAD

**Issue by strahlw** [NEMRI-org/primo-optimizer#60]
The map utility currently only checks for two specific column names from the shapefile data (NAME and COUNTY_NAME). However, depending on the source, the name of the column that corresponds to the county name may be different (in the case of the Colorado, it is "COUNTY"), which will require source code editing to make functional. I suggest that the column name be added as an argument to the function that requires the user to specify what column the county name is in. However, there may be many other ways to address this issue.

**Comment by apd-ypuranik** [comment]
Addressed in #72
